[platformio]
default_envs = esp32c3_v3_8inch

[common]
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D LED_DATA_PIN=10
  -D STATUS_LED_PIN=-1
  -D CENTER_PIXEL_ENABLED=1
  -D ENABLE_WIFI_UI=1
  -D ENABLE_NTP=1
  -D TEMP_SENSOR_ENABLED=0
  -D CLOCK_VARIANT_XIAO_ESP32C3=1
  -D WIFI_CONNECT_TIMEOUT_MS=20000
  -D WIFI_SSID=\"MAINFRAME005\"
  -D WIFI_PASSWORD=\"Secure!4\"
  -D NTP_TIMEZONE_TZ=\"MST7MDT,M3.2.0,M11.1.0\"
  -D LUX_SENSOR_ENABLED=1
  -D LUX_SENSOR_I2C_SDA=6
  -D LUX_SENSOR_I2C_SCL=7
  -D FIRMWARE_VERSION='"2.3.2"'
  -D BUTTON_UP_PIN=5
  -D BUTTON_DOWN_PIN=9

[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool
build_flags =
  -Os
  -flto
lib_deps =
  adafruit/Adafruit NeoPixel @ ^1.12.3
  adafruit/Adafruit VEML7700 Library @ ^2.1.6
  tzapu/WiFiManager @ ^2.0.13

[env:esp32c3_v3_8inch]
build_flags =
  ${common.build_flags}
  -D CLOCK_VARIANT_8INCH=1
  -D DEVICE_TITLE=\"esp32c3-v3-8inch\"
  -D DEVICE_HOSTNAME=\"esp32c3-v3-8inch\"
  -D CLOCK_PIXEL_COUNT=98
  -D CENTER_PIXEL_INDEX=97
  -D RING_PIXEL_OFFSET=1
  -D SACRIFICIAL_PIXEL_ENABLED=1
  -D SACRIFICIAL_PIXEL_INDEX=0
upload_protocol = esptool
upload_port = COM6

[env:esp32c3_v3_15inch]
build_flags =
  ${common.build_flags}
  -D CLOCK_VARIANT_15INCH=1
  -D DEVICE_TITLE=\"esp32c3-v3-15inch\"
  -D DEVICE_HOSTNAME=\"esp32c3-v3-15inch\"
  -D CLOCK_PIXEL_COUNT=96
  -D CENTER_PIXEL_SEPARATE_OUTPUT=1
  -D CENTER_PIXEL_PIN=20
  -D CENTER_PIXEL_STRIP_COUNT=1
  -D CENTER_PIXEL_INDEX=0
  -D RING_PIXEL_OFFSET=0
  -D SACRIFICIAL_PIXEL_ENABLED=0
upload_protocol = esptool
upload_port = COM9
